- name: cleanup
  steps:
    - name: cleanup-workspace
      image: alpine
      script: |
        rm -rf /workspace/*
- name: nose-tests
  steps:
    - name: run-tests
      image: python:3.9-slim
      script: |
        pip install -r requirements.txt
        pip install nose
        nosetests