apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup-workspace
      image: alpine:3
      script: |
        rm -rf $(workspaces.source.path)/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install -r requirements.txt
        pip install nose
        nosetests
